import NextAuthProvider from "./NextAuthProvider";
import type { Metadata } from "next";
import { SiteNavigation } from "@/app/components/navigations/SiteNav";
import { ThemeProvider } from "@/app/components/theme-provider";
import "../globals.css";

export const metadata: Metadata = {
  title: "Future",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <NextAuthProvider>
        <body className="bg-primary-bg dark:bg-dark-primary-bg min-h-screen">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SiteNavigation />
            <main className="p-20">{children}</main>
          </ThemeProvider>
        </body>
      </NextAuthProvider>
    </html>
  );
}
